/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsParodiesRouteImport } from './routes/sports-parodies'
import { Route as OtherWorksRouteImport } from './routes/other-works'
import { Route as EstrusRouteImport } from './routes/estrus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'

const SportsParodiesRoute = SportsParodiesRouteImport.update({
  id: '/sports-parodies',
  path: '/sports-parodies',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherWorksRoute = OtherWorksRouteImport.update({
  id: '/other-works',
  path: '/other-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrusRoute = EstrusRouteImport.update({
  id: '/estrus',
  path: '/estrus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/estrus': typeof EstrusRoute
  '/other-works': typeof OtherWorksRoute
  '/sports-parodies': typeof SportsParodiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/estrus': typeof EstrusRoute
  '/other-works': typeof OtherWorksRoute
  '/sports-parodies': typeof SportsParodiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/estrus': typeof EstrusRoute
  '/other-works': typeof OtherWorksRoute
  '/sports-parodies': typeof SportsParodiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/contact'
    | '/estrus'
    | '/other-works'
    | '/sports-parodies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/contact'
    | '/estrus'
    | '/other-works'
    | '/sports-parodies'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/contact'
    | '/estrus'
    | '/other-works'
    | '/sports-parodies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  EstrusRoute: typeof EstrusRoute
  OtherWorksRoute: typeof OtherWorksRoute
  SportsParodiesRoute: typeof SportsParodiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports-parodies': {
      id: '/sports-parodies'
      path: '/sports-parodies'
      fullPath: '/sports-parodies'
      preLoaderRoute: typeof SportsParodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-works': {
      id: '/other-works'
      path: '/other-works'
      fullPath: '/other-works'
      preLoaderRoute: typeof OtherWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrus': {
      id: '/estrus'
      path: '/estrus'
      fullPath: '/estrus'
      preLoaderRoute: typeof EstrusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  EstrusRoute: EstrusRoute,
  OtherWorksRoute: OtherWorksRoute,
  SportsParodiesRoute: SportsParodiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
